<trans>
Case(
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Name$ == '71300 - SIS Corp SpecOps','Off Duty Officer',
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Name$ == '20180 - Cupertino Secure Destruction','Off Duty Officer',
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Name$ == '20190 - Cupertino Secure Storage (RC09)','Off Duty Officer',
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Name$ == '50000 - Special Operations - Secure Logistics','Off Duty Officer',
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Name$ == '55110 - Apple Corp. Engineer Escort, Field Engineering Campus','Off Duty Officer',
root$transaction.response$body$queryResponse$result$records.Contact$Master_Job_Code_For_Time_Keeping__r$Division__c$ == 'Operations','Campus',
true,''
);
</trans>